# Numpy

In [82]:
import numpy as np

Create Array

In [ ]:
l=range(1000000)

In [81]:
np.arange(1000000)

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [4]:
x=np.arange(10)

In [6]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

ndarray OF Attributes

In [13]:
import numpy as np

In [35]:
a = np.arange(15).reshape(3, 5)


In [22]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
a.ndim

2

In [26]:
a.dtype

dtype('int32')

In [30]:
a.itemsize

4

In [31]:
a.data

In [32]:
a.size

15

In [36]:
n=np.zeros((5,5))

In [37]:
n

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
s=np.ones((7,7))

In [39]:
s

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [40]:
a=np.empty((5,5))

In [41]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

create sequences of numbers

In [47]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [49]:
np.dtype

numpy.dtype

In [52]:
np.arange(50,200,10)


array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
       180, 190])

In [54]:
np.arange(0.,10,.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

Vetorized Operation

In [58]:
a=np.random.randn((10))

In [62]:
a

array([ 0.49929553, -0.10810165,  0.97343227, -0.54352061,  0.25769107,
       -0.30496737, -0.17338167, -0.7916097 ,  0.86738516,  0.9222992 ])

In [63]:
x=np.random.randn((10))

In [64]:
x

array([-0.56783245,  1.34256042,  0.67071277,  0.63571213, -1.52756803,
        0.74857983, -0.65397137,  0.92920105,  1.04810415, -0.43018576])

In [65]:
a+x

array([-0.06853692,  1.23445877,  1.64414504,  0.09219152, -1.26987697,
        0.44361245, -0.82735303,  0.13759135,  1.91548931,  0.49211344])

In [66]:
a*x

array([-0.2835162 , -0.145133  ,  0.65289346, -0.34552265, -0.39364064,
       -0.22829243,  0.11338665, -0.73556456,  0.90910999, -0.39675998])

In [67]:
b=np.random.gamma((10))

In [68]:
b

7.606159555513724

In [70]:
a%b

array([0.49929553, 7.4980579 , 0.97343227, 7.06263895, 0.25769107,
       7.30119218, 7.43277789, 6.81454986, 0.86738516, 0.9222992 ])

In [76]:
y=np.array( [[2,3],[3,4]] )


In [77]:
y

array([[2, 3],
       [3, 4]])

Boolean Array

In [83]:
z= np.array([4, 4, 4, 4, 4, 4])
print(z == 4)

[ True  True  True  True  True  True]


In [117]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr=arr1==arr2
arr

array([[False, False, False],
       [False, False, False]])

Indexing Slicing

In [84]:
d=np.array([1,2,4,6,8,9,10,17])

In [85]:
d[4]

8

In [86]:
d[d<6]

array([1, 2, 4])

In [87]:
d[[3,5]]

array([6, 9])

In [88]:
w=np.random.randn(12,10)

In [89]:
w

array([[ 8.29227440e-01, -5.99543544e-04,  1.33363291e-01,
        -1.73821966e+00,  7.79627266e-01,  1.07098550e+00,
         4.37149872e-01,  1.62374765e+00,  2.08556516e-01,
         3.96551844e-01],
       [ 1.37156672e+00,  2.95525667e+00,  1.18441512e+00,
         1.06514547e+00, -7.84852367e-01, -1.80190084e+00,
        -5.51839420e-01, -4.42000673e-01,  1.61446076e+00,
         1.24943852e+00],
       [-1.52037300e-01, -1.68470761e-01, -2.12959995e-02,
         1.30310629e+00,  7.77857763e-01,  8.11929449e-01,
        -1.65156849e+00,  4.79643644e-01,  2.52695680e+00,
         5.11595818e-01],
       [ 1.18197148e+00,  3.05195335e-01,  1.59350477e+00,
         1.90331331e+00,  1.06105637e+00, -3.19016062e-01,
         1.46871274e+00,  6.68357538e-01, -1.94979423e+00,
         1.08384638e+00],
       [-5.43291147e-01,  1.83097695e+00, -3.16213769e-01,
         2.77491219e-01, -2.79016076e+00, -9.80100940e-01,
        -9.51547175e-01,  1.95625931e+00, -5.59402171e-01,
        -5.

In [90]:
w[3]

array([ 1.18197148,  0.30519534,  1.59350477,  1.90331331,  1.06105637,
       -0.31901606,  1.46871274,  0.66835754, -1.94979423,  1.08384638])

In [91]:
w[1:10:3]

array([[ 1.37156672,  2.95525667,  1.18441512,  1.06514547, -0.78485237,
        -1.80190084, -0.55183942, -0.44200067,  1.61446076,  1.24943852],
       [-0.54329115,  1.83097695, -0.31621377,  0.27749122, -2.79016076,
        -0.98010094, -0.95154718,  1.95625931, -0.55940217, -0.52222341],
       [ 0.74695534,  1.48796462, -0.55514785, -1.3810656 ,  0.33136681,
        -0.56300272,  0.40863472,  0.10821535, -0.96495362,  1.22116155]])

In [92]:
w[1:-2]

array([[ 1.37156672,  2.95525667,  1.18441512,  1.06514547, -0.78485237,
        -1.80190084, -0.55183942, -0.44200067,  1.61446076,  1.24943852],
       [-0.1520373 , -0.16847076, -0.021296  ,  1.30310629,  0.77785776,
         0.81192945, -1.65156849,  0.47964364,  2.5269568 ,  0.51159582],
       [ 1.18197148,  0.30519534,  1.59350477,  1.90331331,  1.06105637,
        -0.31901606,  1.46871274,  0.66835754, -1.94979423,  1.08384638],
       [-0.54329115,  1.83097695, -0.31621377,  0.27749122, -2.79016076,
        -0.98010094, -0.95154718,  1.95625931, -0.55940217, -0.52222341],
       [-1.43602903, -1.44166239,  1.00840396, -0.12480576,  0.8099038 ,
        -0.76034977, -0.59223042,  1.09185821,  0.87501792,  0.24004611],
       [-0.24802513,  0.3902108 , -2.09978922,  0.36229204, -0.68122392,
         0.4065291 ,  1.0803124 , -0.70375368, -0.10378499, -1.23327111],
       [ 0.74695534,  1.48796462, -0.55514785, -1.3810656 ,  0.33136681,
        -0.56300272,  0.40863472,  0.10821535

Function

In [95]:
a=np.array([2,4,6,9,7,10])

In [96]:
np.sqrt(a)

array([1.41421356, 2.        , 2.44948974, 3.        , 2.64575131,
       3.16227766])

In [97]:
c=np.array([12,24,56,47,31])

In [107]:
np.power(c,2)

array([ 144,  576, 3136, 2209,  961], dtype=int32)

In [113]:
np.sqrt(c)

array([3.46410162, 4.89897949, 7.48331477, 6.8556546 , 5.56776436])

Reverse a Vector    

In [116]:
a=np.array([1,3,6,4,7])
print(a)
print(a[-1::-1])

[1 3 6 4 7]
[7 4 6 3 1]


linear Algebre

In [168]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

array([[1., 2.],
       [3., 4.]])

In [174]:
b = np.array([[2,5], [4,6]])
b

array([[2, 5],
       [4, 6]])

In [175]:
a.trace()

5.0

In [169]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [172]:
np.linalg.inv(a)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [173]:
a.sum()

10.0

In [178]:
a.dot(b)

array([[10., 17.],
       [22., 39.]])

In [181]:
a.prod()

24.0

Replace all odd numbers in arr 



In [119]:
arr=np.arange(0,20,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18])

Replace the values of indexes 5,7,6 and 8 to **14**

In [120]:
na=np.arange(0,15)
na[5]=14
na[7]=14
na[6]=14
na[8]=14
na

array([ 0,  1,  2,  3,  4, 14, 14, 14, 14,  9, 10, 11, 12, 13, 14])

 Convert a 1D array to a 2D array with 2 rows

In [136]:
arr=np.arange(10)
arr.reshape(2,-1)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [137]:
arr = np.arange(20)
arr.reshape(2, -2)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [148]:
a=np.arange(30,2,2)
a.reshape(3,-3)

array([], shape=(3, 0), dtype=int32)

In [149]:
a=np.arange(30)
a.reshape(3,-3)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

Concatenate

In [161]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)


In [158]:
np.concatenate([a ,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [162]:
np.concatenate([a ,b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

where

In [163]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b,a,b)

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [2]:
[i for i in range(100000000)][:20000000]
%time


Wall time: 0 ns


In [14]:
[i for i in range(100000)][:200:5]


[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195]